title: Keisuke Ogawa
logo: /assets/img/personal/headshot2.png
description: Robotics and AI-focused engineer with 5+ years professional experience in Amazon, developing mobile robots and manipulation with interests in perception, multimodal learning, and physical AI.
show_downloads: false
theme: jekyll-theme-minimal
email: "ogawa3@illinois.edu"
linkedin: "https://www.linkedin.com/in/keisuke-ogawa-2624a3154/"
